### ISSUE TITLE
Cant start the QwikSwitch USB Hub service (parse error)

### ISSUE THREAD

**Issue by andrew-w-roberts** [nardusleroux/hassio-qsusb#10]
-----------------------------------------------------------
 Hass.io Add-on: QwikSwitch USB Hub
 Add-on for the QwikSwitch USB Hub
-----------------------------------------------------------
 Add-on version: 0.92
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[14:25:41] ERROR: Unknown HTTP error occured
 System:   (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.1.1
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
I have checked the config and cant find anything obviously wrong - the network host is set to disabled - could that have anything to do with it?

![QwikSwitch USB Hub Network Config ](https://user-images.githubusercontent.com/38247703/104593561-8c02f380-5678-11eb-96cc-0d8a5e9c81b0.png)

**Comment by kellerza** [comment]
Hi @andrew-w-roberts . I also had this error, but it was never serious & the addon worked with it. I suspect it's from the base build images since it is not part of the `run.sh` script at all.

There seem to be more serious issues now and the current version is not working with Supervisor version 2021.02 onward at all.

Further down in the logs I get this:

```bash
LS
-rwxr-xr-x 1 root root 78257 Mar 15  2016 /qsusb/QSUSB/qsusb
Starting
./run.sh: line 28: /qsusb/QSUSB/qsusb: No such file or directory
[cmd] ./run.sh exited 127
```

**No such file or directory** is likely from QSUSB not picking up the USB modem on the Pi4

**Comment by andrew-w-roberts** [comment]
Hi @Kellerza, I have had that error too. I havent been able to get the QSUSB to work yet so I unfortunately dont have any pointers for you. It is a great shame. I am not going to replace all the Qwikswitches throughout the house so I'm afraid that could mean the end of the HA platform :-( such a pity.

**Comment by nardusleroux** [comment]
Hi @andrew-w-roberts 
Have you used 0.93? Works fine for me. The error you report I have as well and as indicated by @kellerza is part of ubuntu-base that is used.

Here is my log but qsusb is working in HA.


```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: QwikSwitch USB Hub
 Add-on for the QwikSwitch USB Hub
-----------------------------------------------------------
 Add-on version: 0.93
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[21:16:45] ERROR: Unknown HTTP error occured
 System:   (armv7 / raspberrypi4)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
.
ENVIRONMENT - DOCKER BUILD
FILE=qsusb_pi_V1.91.zip
BUILD_VERSION=0.93
BUILD_ARCH=armv7
.
ENVIRONMENT - DOCKER RUN
SUPERVISOR_TOKEN=72972eb67431a7ceecb280d5259e1ccd4f3ca703f2962e64f224b8b528f509de9d379e3631af74f9965dc30e5c02a87711c929e1dad552b0
LANG=C.UTF-8
TZ=Africa/Johannesburg
HOSTNAME=local-qsusb
S6_BEHAVIOUR_IF_STAGE2_FAILS=2
S6_CMD_WAIT_FOR_SERVICES=1
HASSIO_TOKEN=72972eb67431a7ceecb280d5259e1ccd4f3ca703f2962e64f224b8b528f509de9d379e3631af74f9965dc30e5c02a87711c929e1dad552b0
PWD=/qsusb
HOME=/root
S6_LOGGING=0
DEBIAN_FRONTEND=noninteractive
TERM=xterm-256color
SHLVL=1
CWD=/qsusb
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/printenv
.
DEVICES CONFIG
@129b70/rel/Sitkamer tafel lamp
@16aa30/rel/Sitkamer staan lamp
.
LS
-rwxr-xr-x 1 root root 78257 Mar 15  2016 /qsusb/QSUSB/qsusb
Starting
QSUSB V1.91
DEBUG=0
LOGS=0
Listening on Port: 2020
Devices Loaded:2
Crons loaded: 0
USB Found
```

**Comment by andrew-w-roberts** [comment]
Epic! @nardusleroux, thank you! I really appreciate the advice. Let me try revert back to that branch and see if I can get it to work...

**Comment by kellerza** [comment]
0.93 does not work on my Pi4 either:



Towards the end of the log you get this. (This must be qsusb's internals, since the file is executable in Docker (see the ls command just above that)

```
LS
-rwxr-xr-x 1 root root 78257 Mar 15  2016 /qsusb/QSUSB/qsusb
Starting
./run.sh: line 28: /qsusb/QSUSB/qsusb: No such file or directory
[cmd] ./run.sh exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

Version 0.93 (also still has the http error I'm still not worried about...

```
-----------------------------------------------------------
 Hass.io Add-on: QwikSwitch USB Hub
 Add-on for the QwikSwitch USB Hub
-----------------------------------------------------------
 Add-on version: 0.93
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[08:49:14] ERROR: Unknown HTTP error occured
 System:   (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.2.3
 Home Assistant Supervisor: 2021.02.9
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

Since the `qsusb` executable fails, complaining about not finding a file:
- Closest issues I could find: https://github.com/home-assistant/supervisor/issues/2558
- I also noticed that the qsusb modem is (in?)correctly picked up as `/dev/usb/hiddev0`. Unbinding this does nothing.

At a bit of a stalemate, but I still have some really old Pi's lying around that runs qsusb for me at the moment

**Comment by kellerza** [comment]
Notice now @nardusleroux has `armv7` and I have `aarch64`, so maybe 64-bit support is now broken :-(

**Comment by andrew-w-roberts** [comment]
@nardusleroux, I have just checked and I too am on 0.93. my PI4 is on 64bit
@Kellerza, what version are you running on?
Do you think we could try reloading an old version of HA on 32bit and then try using an older branch of the QSUSB?

**Comment by ipodmusicman** [comment]
I am on a Pi4, but with 32 bit.  I haven't attempted to venture into upgrading to 64 bit as yet.  On my environment, it is working perfectly, but ideally, we'd want to allow 64 bit support.

@andrew-w-roberts you can re-install the latest HA on your Pi, but using the 32 bit version instead and it should work just fine.

Anybody willing to figure out how to adjust the plugin to support 64 bit?  I would think that the qsusb should run regardless of OS architecture?

**Comment by kellerza** [comment]
Expecting my USB3 SSD on Friday and will move to 32-bit as well. 

With a 4GB Pi4 there should be no difference between x32/x64

**Comment by ipodmusicman** [comment]
I would think that the reason why one would want to go 64 bit is to use the VSCode add-ons and other add-ons that are currently disabled due to not being supported on 32 bit.  It has been tempting though.

**Comment by nardusleroux** [comment]
Yep, I am running 32bit (armv7) since HA recommended for rpi4 was 32bit at least last I looked. This may have been updated in meanwhile. Have not tried to get 64bit architecture going or tested since not needed.

**Comment by nardusleroux** [comment]
If 64bit support is needed lets look at this as enhancement.

**Comment by kellerza** [comment]
To be honest, I might even have been on the 32-bit architecture before...

By the time the February supervisor ~~messup~~update happened, we've had too much load-shedding & I've seen other unexplained behaviour. I started by ordering an SSD & burned a fresh SD card with the 64-bit version.

I do not have a preference and happy with either `vi` or that basic "file editor" for tinkering with yaml

**Comment by andrew-w-roberts** [comment]
Guys! It works! I reinstalled from scratch using the 32 bit and the Q USB hib now works - wow! Thank you!!!

**Comment by nardusleroux** [comment]
Closing since seemingly resolved.
