### ISSUE TITLE
Allow usb through to the add-on

### ISSUE THREAD

**Issue by ipodmusicman** [nardusleroux/hassio-qsusb#11]
Hi there,

I found that after upgrading to HassOS 5.11, the QS USB was not able to find the USB port.  I tested by adding "usb": true into the config.json and that sorted it out. 

Can either Nardus or Johan please make the change?  I'll see if I can do it this weekend if any of you two are not able to this week.  At present I'm running the add-on locally so that my lights can work again.

**Comment by kellerza** [comment]
Hi @ipodmusicman, if you can look into this over the weekend it would be great, thanks!!

**Comment by ipodmusicman** [comment]
@nardusleroux pull request created.

**Comment by nardusleroux** [comment]
Thank you @ipodmusicman for update! Merged and this is building fine for me and working in home-assistant core 2021.02.3 and supervisor 2021.02.6.
