### ISSUE TITLE
Does this work on version 2021.3.0 - 64bit Version Raspberry Pi 3?

### ISSUE THREAD

**Issue by pedrodagraca** [nardusleroux/hassio-qsusb#14]
Hi all,

Below is the output in my log file:

ENVIRONMENT - DOCKER BUILD
FILE=qsusb_pi_V1.91.zip
BUILD_VERSION=0.93
BUILD_ARCH=aarch64

....

PWD=/qsusb
HOME=/root
S6_LOGGING=0
DEBIAN_FRONTEND=noninteractive
TERM=xterm-256color
SHLVL=1
CWD=/qsusb
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/printenv
.
DEVICES CONFIG
@129b70/rel/Study lamp
@16aa30/rel/Kitchen lamp
.
LS
-rwxr-xr-x 1 root root 78257 Mar 15  2016 /qsusb/QSUSB/qsusb
Starting
./run.sh: line 28: /qsusb/QSUSB/qsusb: No such file or directory
[cmd] ./run.sh exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by nardusleroux** [comment]
Hi @pedrodagraca 
Currently only 32bit architecture supported. I can make this clearer in readme. Have not looked at 64bit at all. Possible enhancement in future.

**Comment by pedrodagraca** [comment]
Hey @nardusleroux  thanks for the quick response. I was just about to go in and close this as last night I realised it is only 32bit and reflashed my SD card with HA OS 32-bit. All's working well now with your Qwikswitch add-on.

Well done on the excellent work you've done with this, it has saved some of us a lot of time!

If I find some time I may look at the 64bit version.

**Comment by nardusleroux** [comment]
You are welcome, lots of contributions from community. Closing issue.
