### ISSUE TITLE
Can't build local/armv7-addon-qsusb:0.7

### ISSUE THREAD

**Issue by TinesPotgieter** [nardusleroux/hassio-qsusb#2]
Something happen last night on my hassIO, qsusb stopped working, when removing and attempting to reinstall get the following error, if you have any idea how to fix. 

ERROR (SyncWorker_16) [hassio.docker.addon] Can't build local/armv7-addon-qsusb:0.7: The command '/bin/sh -c apt-get update && apt-get install -q -y --no-install-recommends     libusb-1.0     unzip     wget     jq' returned a non-zero code: 127

**Comment by TinesPotgieter** [comment]
Issue with the following lines in the docker file.

RUN apt-get update && apt-get install -q -y --no-install-recommends \
    libusb-1.0 \
    unzip \
    wget \
    jq

any advise how to get around this?

**Comment by ipodmusicman** [comment]
Hi @TinesPotgieter 

I've made some corrections and created a Pull Request.  Hopefully @nardusleroux will approve soon.

**Comment by nardusleroux** [comment]
Merged. Thanks for looking into this.

**Comment by PollieKrismis** [comment]
I'm having a similar issue...

`19-06-22 10:52:36 ERROR (SyncWorker_9) [hassio.docker.addon] Can't build local/armv7-addon-qsusb:0.8: The command '/bin/bash -o pipefail -c FILE="qsusb_pi_V1.91.zip"     && if [ "${BUILD_ARCH}" = "armhf" ]         || [ "${BUILD_ARCH}" = "armv7" ]         || [ "${BUILD_ARCH}" = "aarch64" ]; then         FILE="qsusb_pi_V1.91.zip";     fi     && if [ "${BUILD_ARCH}" = "i386" ]         || [ "${BUILD_ARCH}" = "amd64" ]; then         FILE="QSUSB_linux.zip";     fi     && apt-get update         && apt-get install -y --no-install-recommends         libusb-1.0         unzip         wget         jq         && wget https://cdn.shopify.com/s/files/1/1883/0535/files/${FILE}         && unzip ${FILE}' returned a non-zero code: 127`

Should I revert back to the older command? /bin/sh?

**Comment by nardusleroux** [comment]
Hi @PollieKrismis 
Can you use the test branch (qsusb 0.6) and let me know whether this works for you? Just build from test branch on hass.io 0.94.4 and all ok.

**Comment by PollieKrismis** [comment]
@nardusleroux Thank you, that did the trick.
