### ISSUE TITLE
Not working for qsusb on Pi3 B using hassio

### ISSUE THREAD

**Issue by rezizter** [nardusleroux/hassio-qsusb#4]
Hi
I have installed the latest hassio image and am using it on a Pi 3 B

I have installed the repo, and have plugged in the qausb wifi bridge, but still unable to detect device.

Any advise?

**Comment by ipodmusicman** [comment]
This add-on is not for the WiFi Bridge but for the QS USB Hub. The WiFi
Bridge is not capable of direct communication. If you don’t have one,
contact Qwikswitch and they’ll arrange one for you. They don’t have it on
their website but they will sell you one.

**Comment by rezizter** [comment]
Thank you, will do
